---
- name: Check if babashka is installed
  stat:
    path: "{{ _babashka_binary_install_dir }}/bb"
  register: __babashka_is_installed
  check_mode: false
  tags:
    - babashka_install

- block:
    - name: Get latest release
      uri:
        url: "https://api.github.com/repos/babashka/babashka/releases/latest"
        method: GET
        return_content: true
        status_code: 200
        body_format: json
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"
      register: _latest_release
      until: _latest_release.status == 200
      retries: 5

    - name: "Set babashka version to {{ _latest_release.json.tag_name[1:] }}"
      set_fact:
        babashka_version: "{{ _latest_release.json.tag_name[1:] }}"
  when:
    - babashka_version == "latest"
    - babashka_binary_local_dir | length == 0
  delegate_to: localhost
  run_once: true

  #- block:
  #    - name: Get checksum list from github
  #      set_fact:
  #        _checksums: "{{ lookup('url', 'https://github.com/babashka/babashka/releases/download/v' + babashka_version + '/sha256sums.txt', wantlist=True) | list }}"
  #      run_once: true
  #
  #    - name: "Get checksum for {{ arch }} architecture"
  #      set_fact:
  #        babashka_checksum: "{{ item.split(' ')[0] }}"
  #      with_items: "{{ _checksums }}"
  #      when:
  #        - "('linux-' + arch + '.tar.gz') in item"
  #  delegate_to: localhost
  #  when: babashka_binary_local_dir | length == 0
